name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: mparchin
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
        push: true
        tags: mparchin/qbittorrent_fix_stalled:${{ github.ref_name }},mparchin/qbittorrent_fix_stalled:latest
